version: 2
updates:
# Fetch and update latest `npm` packages
- package-ecosystem: npm
  directory: '/'
  schedule:
    interval: monthly
    time: '00:00'
	target-branch: "dev"
  open-pull-requests-limit: 10
  reviewers:
    - olivermanzi
  assignees:
    - olivermanzi
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
