services:
  server:
    image: samdruant-server
    build: ./server
    ports:
      - "3001:3001"
    env_file:
      - ./server/.env.dev
    environment:
      - NODE_ENV=development # ensures that .dotenv uses the .env.dev file
      - DB_URI=mongodb://host.docker.internal:27017/samdruant  # host.docker.internal is the host machine IP
  client:
    image: samdruant-client
    build: ./client
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env
    depends_on:
      - server