services:
  server:
    image: samdruant-server
    build: ./server
    env_file:
      - ./server/.env
    ports:
      - "3001:3001"
  client:
    image: samdruant-client
    build: ./client
    ports:
      - "80:3000"
    env_file:
      - ./client/.env
    depends_on:
      - server