apiVersion: apps/v1
kind: Deployment
metadata:
  name: sam-server
  labels:
    app: sam
    component: server

spec:
  replicas: 1
  selector:
    matchLabels:
      app: sam
      component: server
  template:
    metadata:
      labels:
        app: sam
        component: server
    spec:
      containers:
        - name: server
          image: thisoliver/example-kubernates-app:server # <- tag is important
          #image: example-kubernates-app:server # <- local image
          #imagePullPolicy: Never # <- forces k8 controller to use local image
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: sam-secrets # <- value from metadata.name in secrets.yaml
                  key: jwt-secret

            - name: ADMIN_SECRET
              valueFrom:
                secretKeyRef:
                  name: sam-secrets
                  key: admin-secret

            - name: DB_URI
              valueFrom:
                secretKeyRef:
                  name: sam-secrets
                  key: db-uri

            - name: BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: sam-secrets
                  key: bucket-name

            - name: BUCKET_S3_URI
              valueFrom:
                secretKeyRef:
                  name: sam-secrets
                  key: bucket-uri

            - name: BUCKET_S3_REGION
              valueFrom:
                secretKeyRef:
                  name: sam-secrets
                  key: bucket-region

            - name: BUCKET_S3_KEY
              valueFrom:
                secretKeyRef:
                  name: sam-secrets
                  key: bucket-key

            - name: BUCKET_S3_SECRET
              valueFrom:
                secretKeyRef:
                  name: sam-secrets
                  key: bucket-secret

          ports:
            - containerPort: 4000
              name: server-port
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sam-client
  labels:
    app: sam
    component: client

spec:
  replicas: 1
  selector:
    matchLabels:
      app: sam
      component: client
  template:
    metadata:
      labels:
        app: sam
        component: client
    spec:
      containers:
        - name: client
          image: thisoliver/example-kubernates-app:client # <- tag is important
          #image: example-kubernates-app:client # <- local image
          #imagePullPolicy: Never # <- forces k8 controller to use local image
          env:
            - name: NUXT_PUBLIC_API_BASE
              value: http://sam-server:5050
          ports:
            - containerPort: 3000
              name: client-port
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
