services:
  server:
    image: samdruant-server
    build: ../packages/server
    env_file:
      - ../packages/server/.env
    ports:
      - "4000:5000"
  client:
    image: samdruant-client
    build: ../packages/client
    ports:
      - "80:3000"
    environment:
      - NUXT_PUBLIC_BASE_URL=http://localhost:4000/api
    depends_on:
      - server