services:
  server:
    image: samdruant-server
    build: ../packages/server
    env_file:
      - ../packages/server/.env
    ports:
      - "4000:4000"
  client:
    image: samdruant-client
    build: ../packages/client
    ports:
      - "80:3000"
    env_file:
      - ../packages/client/.env
    depends_on:
      - server