# Secret resource for storing sensitive information like API tokens and secrets.
apiVersion: v1
kind: Secret
metadata:
  name: sam
type: Opaque
data:
  ADMIN_JWT_SECRET: c3VwZXItdG9wLXNlY3JldAo= # "super-top-secret" in base64 encoding
  API_TOKEN_SALT: c3VwZXItdG9wLXNlY3JldAo=
  APP_KEYS: c3VwZXItdG9wLXNlY3JldAo=
  JWT_SECRET: c3VwZXItdG9wLXNlY3JldAo=
  NUXT_API_TOKEN: c3VwZXItdG9wLXNlY3JldAo=
---
# Secret resource for storing registry credentials.
apiVersion: v1
kind: Secret
metadata:
  name: regcred
type: kubernetes.io/dockercfg
data:
  .dockercfg: |
    eyJhdXRocyI6eyJodHRwczovL2V4YW1wbGUvdjEvIjp7ImF1dGgiOiJvcGVuc2VzYW1lIn19fQo=
