# This is a Secret config and it is used to define the environment variables
# that will be used in the deployment.yaml file. The config defines
# the jwt-secret environment variable that is used in the server container
# in the deployment.yaml file.

apiVersion: v1
kind: Secret
metadata:
  name: sam

type: Opaque
data:
  ADMIN_JWT_SECRET: c3VwZXItdG9wLXNlY3JldAo= # "super-top-secret" in base64 encoding
  API_TOKEN_SALT: c3VwZXItdG9wLXNlY3JldAo=
  APP_KEYS: c3VwZXItdG9wLXNlY3JldAo=
  JWT_SECRET: c3VwZXItdG9wLXNlY3JldAo=
  NUXT_API_TOKEN: c3VwZXItdG9wLXNlY3JldAo=
