apiVersion: v1
kind: Service
metadata:
  name: sam
  labels:
    app: sam

spec:
  type: NodePort
  selector:
    app: sam

  ports:
    - protocol: TCP
      port: 3000
      targetPort: frontend-port # <- frontend container port in deployment.yaml
    - protocol: TCP
      port: 1337
      targetPort: backend-port # <- client container port in deployment.yaml
