name: CD Frontend
on:
  push:
    branches: [main]
    paths:
      - "src/frontend/**"

jobs:
  deploy-frontend:
    uses: ./.github/workflows/cd.yaml
    with:
      app: frontend
    secrets: inherit
