name: CI Backend
on:
  pull_request:
    branches: [main]
    types: [opened, edited, synchronize]
    paths:
      - ".github/workflows/**"
      - "k8s/**"
      - "src/backend/**"

jobs:
  backend-ci:
    uses: ./.github/workflows/ci.yaml
    with:
      app: backend
    secrets: inherit
