name: CI Frontend
on:
  pull_request:
    branches: [main]
    types: [opened, edited, synchronize]
    paths:
      - "src/frontend/**"

jobs:
  frontend-ci:
    uses: ./.github/workflows/ci.yaml
    with:
      app: frontend
    secrets: inherit
